import React,{useCallback,useEffect,useState} from 'react';
import {View,Text,FlatList,StyleSheet,ActivityIndicator} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {PhoneIncoming,PhoneOutgoing,PhoneMissed} from 'lucide-react-native';
import {supabase} from '../../lib/supabase'; import {useAuth} from '../../context/AuthContext';
export default function CallHistoryScreen(){const{user}=useAuth();const[rows,setRows]=useState<any[]>([]);const[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{if(!user)return;const{data}=await supabase.from('calls').select('*,caller:profiles!calls_caller_id_fkey(display_name),receiver:profiles!calls_receiver_id_fkey(display_name)').or(`caller_id.eq.${user.id},receiver_id.eq.${user.id}`).order('created_at',{ascending:false}).limit(100);setRows(data??[]);setLoading(false)},[user]);
 useEffect(()=>{load();if(!user)return;const c=supabase.channel(`call-history:${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'calls'},load).subscribe();return()=>{supabase.removeChannel(c)}},[user,load]);
 return <SafeAreaView style={s.root}><Text style={s.title}>कॉल हिस्ट्री</Text>{loading?<ActivityIndicator color="#22C55E"/>:<FlatList data={rows} keyExtractor={x=>x.id} renderItem={({item})=>{const outgoing=item.caller_id===user?.id;const other=outgoing?item.receiver:item.caller;const missed=item.status==='missed'||item.status==='rejected';const Icon=missed?PhoneMissed:outgoing?PhoneOutgoing:PhoneIncoming;return <View style={s.row}><Icon color={missed?'#EF4444':'#22C55E'} size={22}/><View style={{flex:1}}><Text style={s.name}>{other?.display_name??'User'}</Text><Text style={s.meta}>{outgoing?'Outgoing':'Incoming'} · {item.status}</Text></View><Text style={s.date}>{new Date(item.created_at).toLocaleDateString()}</Text></View>}}/>}</SafeAreaView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#0B1220'},title:{fontSize:24,fontWeight:'800',color:'#F8FAFC',padding:20},row:{flexDirection:'row',alignItems:'center',gap:14,paddingHorizontal:20,paddingVertical:15,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#1E293B'},name:{color:'#F8FAFC',fontSize:16,fontWeight:'700'},meta:{color:'#94A3B8',marginTop:3},date:{color:'#64748B',fontSize:12}})
