import React from 'react'; import {SafeAreaView} from 'react-native-safe-area-context'; import {View,Text,FlatList,TouchableOpacity,StyleSheet,ActivityIndicator,Alert} from 'react-native'; import {Bell,MessageCircle,UserPlus,UserCheck,PhoneMissed,Check,Trash2} from 'lucide-react-native';
import {useNotifications,AppNotification} from '../../context/NotificationContext'; import {supabase} from '../../lib/supabase';
export default function NotificationsScreen({navigation}:any){const {notifications,unreadCount,loading,markRead,markAllRead,remove}=useNotifications();
 const open=async(n:AppNotification)=>{if(!n.is_read)await markRead(n.id);if(n.type==='message'&&n.related_id)return navigation.navigate('Chat',{conversationId:n.related_id});if((n.type==='friend_request'||n.type==='contact_request')&&n.actor_id)return navigation.navigate('UserProfile',{profileId:n.actor_id});if(n.type==='friend_accepted'&&n.actor_id)return navigation.navigate('UserProfile',{profileId:n.actor_id});if(n.type==='missed_call')return navigation.navigate('Tabs',{screen:'Calls'});Alert.alert('Notification',n.message||n.title)};
 const accept=async(n:AppNotification)=>{if(!n.related_id)return;const{error}=await supabase.from('contacts').update({status:'accepted'}).eq('id',n.related_id);if(error)return Alert.alert('Accept नहीं हुआ',error.message);await markRead(n.id);await remove(n.id)};
 const decline=async(n:AppNotification)=>{if(!n.related_id)return;const{error}=await supabase.from('contacts').delete().eq('id',n.related_id);if(error)return Alert.alert('Decline नहीं हुआ',error.message);await markRead(n.id);await remove(n.id)};
 const icon=(t:string)=>t==='message'?<MessageCircle color="#60A5FA"/>:t==='friend_request'||t==='contact_request'?<UserPlus color="#F59E0B"/>:t==='friend_accepted'?<UserCheck color="#22C55E"/>:t==='missed_call'?<PhoneMissed color="#F87171"/>:<Bell color="#94A3B8"/>;
 return <SafeAreaView style={s.root} edges={['top']}><View style={s.head}><View><Text style={s.title}>Notifications</Text><Text style={s.sub}>{unreadCount} unread</Text></View>{unreadCount>0&&<TouchableOpacity onPress={markAllRead}><Text style={s.mark}>Mark all read</Text></TouchableOpacity>}</View>{loading?<ActivityIndicator style={{marginTop:40}} color="#22C55E"/>:<FlatList data={notifications} keyExtractor={x=>x.id} ListEmptyComponent={<Text style={s.empty}>कोई notification नहीं है</Text>} renderItem={({item:n})=><TouchableOpacity onPress={()=>open(n)} style={[s.row,!n.is_read&&s.unread]}><View style={s.ico}>{icon(n.type)}</View><View style={{flex:1}}><Text style={s.nt}>{n.title}</Text>{n.message?<Text style={s.msg}>{n.message}</Text>:null}{(n.type==='friend_request'||n.type==='contact_request')&&<View style={s.actions}><TouchableOpacity style={s.accept} onPress={e=>{e.stopPropagation();accept(n)}}><Check color="#fff" size={16}/><Text style={s.bt}>Accept</Text></TouchableOpacity><TouchableOpacity style={s.decline} onPress={e=>{e.stopPropagation();decline(n)}}><Text style={s.bt}>Decline</Text></TouchableOpacity></View>}</View><TouchableOpacity onPress={e=>{e.stopPropagation();remove(n.id)}}><Trash2 color="#64748B" size={18}/></TouchableOpacity></TouchableOpacity>}/>}</SafeAreaView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#070D18'},head:{height:72,paddingHorizontal:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:'#172033'},title:{color:'#fff',fontSize:22,fontWeight:'800'},sub:{color:'#64748B',fontSize:12,marginTop:2},mark:{color:'#60A5FA',fontWeight:'700'},row:{flexDirection:'row',gap:12,padding:16,borderBottomWidth:1,borderBottomColor:'#131C2B',alignItems:'flex-start'},unread:{backgroundColor:'#0C1B30'},ico:{width:42,height:42,borderRadius:21,backgroundColor:'#111C2E',alignItems:'center',justifyContent:'center'},nt:{color:'#F8FAFC',fontWeight:'700'},msg:{color:'#94A3B8',fontSize:13,marginTop:3},actions:{flexDirection:'row',gap:8,marginTop:10},accept:{backgroundColor:'#16A34A',height:34,paddingHorizontal:12,borderRadius:8,flexDirection:'row',alignItems:'center',gap:5},decline:{backgroundColor:'#334155',height:34,paddingHorizontal:12,borderRadius:8,justifyContent:'center'},bt:{color:'#fff',fontWeight:'700',fontSize:12},empty:{color:'#64748B',textAlign:'center',marginTop:60}});
