import React,{useEffect,useState} from 'react';
import {SafeAreaView} from 'react-native-safe-area-context';
import {View,Text,TextInput,TouchableOpacity,StyleSheet,ActivityIndicator,FlatList,Image,Alert} from 'react-native';
import {Search,UserPlus,UserCheck} from 'lucide-react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {supabase} from '../../lib/supabase';
import {useAuth} from '../../context/AuthContext';

export default function SearchUsersScreen({navigation}:any){
 const {user}=useAuth(); const [q,setQ]=useState(''); const [rows,setRows]=useState<any[]>([]); const [loading,setLoading]=useState(false); const [history,setHistory]=useState<string[]>([]); const [relations,setRelations]=useState<Record<string,any>>({});
 useEffect(()=>{AsyncStorage.getItem('searchHistory').then(v=>v&&setHistory(JSON.parse(v))).catch(()=>{})},[]);
 useEffect(()=>{if(!q.trim()){setRows([]);return} const t=setTimeout(async()=>{setLoading(true);const term=q.trim().replace(/[%(),]/g,'');const{data,error}=await supabase.from('profiles').select('id,display_name,username,avatar_url,bio').or(`username.ilike.%${term}%,display_name.ilike.%${term}%`).neq('id',user?.id||'').limit(10); if(!error){setRows(data||[]);const nh=[term,...history.filter(x=>x!==term)].slice(0,5);setHistory(nh);AsyncStorage.setItem('searchHistory',JSON.stringify(nh)).catch(()=>{}); if(user&&data?.length){const ids=data.map(x=>x.id);const{data:c}=await supabase.from('contacts').select('*').or(`requester_id.eq.${user.id},responder_id.eq.${user.id}`);const map:any={};(c||[]).filter((x:any)=>ids.includes(x.requester_id===user.id?x.responder_id:x.requester_id)).forEach((x:any)=>{const id=x.requester_id===user.id?x.responder_id:x.requester_id; const p:any={accepted:3,pending:2,blocked:1};if(!map[id]||(p[x.status]||0)>(p[map[id].status]||0))map[id]=x});setRelations(map)}} setLoading(false)},300);return()=>clearTimeout(t)},[q,user]);
 const add=async(id:string)=>{if(!user)return;const{error}=await supabase.from('contacts').insert({requester_id:user.id,responder_id:id,status:'pending'});if(error)Alert.alert('Request नहीं भेजी',error.message);else setRelations(v=>({...v,[id]:{requester_id:user.id,responder_id:id,status:'pending'}}))};
 return <SafeAreaView style={s.root} edges={['top']}><View style={s.header}><Text style={s.title}>यूज़र खोजें</Text></View><View style={s.search}><Search color="#64748B" size={20}/><TextInput value={q} onChangeText={setQ} placeholder="नाम या @VoiceID से खोजें" placeholderTextColor="#64748B" style={s.input} autoCapitalize="none"/></View>{!q&&history.length>0&&<View style={s.hist}><Text style={s.label}>हाल की खोज</Text><View style={s.chips}>{history.map(h=><TouchableOpacity key={h} style={s.chip} onPress={()=>setQ(h)}><Text style={s.chipText}>{h}</Text></TouchableOpacity>)}</View></View>}{loading?<ActivityIndicator style={{marginTop:40}} color="#22C55E"/>:<FlatList data={rows} keyExtractor={x=>x.id} contentContainerStyle={{padding:16,gap:10}} ListEmptyComponent={q?<Text style={s.empty}>कोई यूज़र नहीं मिला</Text>:null} renderItem={({item})=>{const r=relations[item.id];return <TouchableOpacity style={s.row} onPress={()=>navigation.navigate('UserProfile',{profileId:item.id})}><View style={s.avatar}>{item.avatar_url?<Image source={{uri:item.avatar_url}} style={s.img}/>:<Text style={s.avatarText}>{(item.display_name||'?')[0].toUpperCase()}</Text>}</View><View style={{flex:1}}><Text style={s.name}>{item.display_name}</Text><Text style={s.username}>@{item.username}</Text></View>{!r&&<TouchableOpacity style={s.add} onPress={(e)=>{e.stopPropagation?.();add(item.id)}}><UserPlus color="#fff" size={18}/><Text style={s.addText}>Add</Text></TouchableOpacity>}{r?.status==='pending'&&<UserCheck color="#EAB308" size={22}/>} {r?.status==='accepted'&&<UserCheck color="#22C55E" size={22}/>}</TouchableOpacity>}}/>}</SafeAreaView>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#0B1220'},header:{padding:20,paddingBottom:10},title:{color:'#fff',fontSize:26,fontWeight:'800'},search:{margin:16,marginTop:8,height:52,borderRadius:16,backgroundColor:'#172033',flexDirection:'row',alignItems:'center',paddingHorizontal:14,gap:10},input:{flex:1,color:'#fff',fontSize:16},hist:{paddingHorizontal:16},label:{color:'#94A3B8',fontSize:12,fontWeight:'700',marginBottom:10},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{backgroundColor:'#1E293B',paddingHorizontal:14,paddingVertical:8,borderRadius:18},chipText:{color:'#CBD5E1'},row:{backgroundColor:'#172033',borderRadius:16,padding:13,flexDirection:'row',alignItems:'center',gap:12},avatar:{width:50,height:50,borderRadius:25,backgroundColor:'#2563EB',alignItems:'center',justifyContent:'center',overflow:'hidden'},img:{width:'100%',height:'100%'},avatarText:{color:'#fff',fontSize:20,fontWeight:'800'},name:{color:'#fff',fontSize:16,fontWeight:'700'},username:{color:'#60A5FA',marginTop:3},add:{backgroundColor:'#2563EB',borderRadius:10,paddingHorizontal:11,height:36,flexDirection:'row',alignItems:'center',gap:5},addText:{color:'#fff',fontWeight:'700'},empty:{color:'#64748B',textAlign:'center',marginTop:40}});
