import React,{useCallback,useEffect,useState} from 'react';
import {View,Text,TouchableOpacity,StyleSheet,ScrollView,TextInput,Switch,Alert,ActivityIndicator,Image} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {User,Shield,Bell,Ban,LogOut,Save,KeyRound,Trash2,Camera} from 'lucide-react-native';
import * as ImagePicker from 'expo-image-picker';
import Constants from 'expo-constants';
import {useAuth} from '../../context/AuthContext'; import {useThemeMode} from '../../context/ThemeContext'; import {supabase} from '../../lib/supabase';
export default function SettingsScreen({navigation}:any){
 const {profile,user,signOut,updateProfile}=useAuth(); const {mode,scheme,setMode,colors}=useThemeMode(); const light=scheme==='light'; const [name,setName]=useState('');const[bio,setBio]=useState('');const[pwd,setPwd]=useState('');const[settings,setSettings]=useState<any>(null);const[blocked,setBlocked]=useState<any[]>([]);const[saving,setSaving]=useState(false);const[uploadingAvatar,setUploadingAvatar]=useState(false);
 useEffect(()=>{setName(profile?.display_name||'');setBio(profile?.bio||'')},[profile]);
 const load=useCallback(async()=>{if(!user)return;const[{data:s},{data:b}]=await Promise.all([supabase.from('user_settings').select('*').eq('user_id',user.id).maybeSingle(),supabase.from('contacts').select('responder_id, profiles(display_name,username,avatar_url)').match({requester_id:user.id,status:'blocked'})]);setSettings(s||{user_id:user.id,contact_requests:'everyone',notify_contact_requests:true});setBlocked(b||[])},[user]);useEffect(()=>{load()},[load]);
 const save=async()=>{if(!user)return;setSaving(true);const{error}=await supabase.from('profiles').update({display_name:name.trim(),bio:bio.trim()}).eq('id',user.id);setSaving(false);if(error)Alert.alert('Profile update नहीं हुआ',error.message);else{await updateProfile();Alert.alert('Saved','Profile updated!')}};
 const uploadAvatar=async()=>{if(!user)return;try{setUploadingAvatar(true);const pick=await ImagePicker.launchImageLibraryAsync({mediaTypes:ImagePicker.MediaTypeOptions.Images,allowsEditing:true,aspect:[1,1],quality:.85});if(pick.canceled)return;const asset=pick.assets[0];let cloudName=Constants.expoConfig?.extra?.cloudinaryCloudName as string|undefined;if(!cloudName&&profile?.avatar_url){const m=String(profile.avatar_url).match(/res\.cloudinary\.com\/([^/]+)\//);cloudName=m?.[1]}if(!cloudName)throw new Error('Cloudinary cloud name नहीं मिला। GitHub Secret CLOUDINARY_CLOUD_NAME जोड़ें।');const apiBase=(Constants.expoConfig?.extra?.apiBaseUrl as string||'https://www.voiceid.online').replace(/\/$/,'');const timestamp=Math.round(Date.now()/1000);const folder='voiceid/avatars';const sigRes=await fetch(`${apiBase}/api/cloudinary-sign`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({timestamp,folder,public_id:user.id})});if(!sigRes.ok)throw new Error(`Signature failed (${sigRes.status})`);const {signature,apiKey}=await sigRes.json();const form:any=new FormData();form.append('file',{uri:asset.uri,name:`avatar-${user.id}.jpg`,type:asset.mimeType||'image/jpeg'} as any);form.append('signature',signature);form.append('api_key',apiKey);form.append('timestamp',String(timestamp));form.append('folder',folder);form.append('public_id',user.id);const up=await fetch(`https://api.cloudinary.com/v1_1/${cloudName}/image/upload`,{method:'POST',body:form});const data=await up.json();if(!up.ok||!data.secure_url)throw new Error(data?.error?.message||'Cloudinary upload failed');const {error}=await supabase.from('profiles').update({avatar_url:data.secure_url}).eq('id',user.id);if(error)throw error;await updateProfile();Alert.alert('Success','Profile photo updated!')}catch(e:any){Alert.alert('Photo upload नहीं हुआ',e?.message||'Unknown error')}finally{setUploadingAvatar(false)}};
 const updateSetting=async(up:any)=>{if(!user)return;const next={...settings,...up,user_id:user.id};const{error}=await supabase.from('user_settings').upsert(next);if(error)Alert.alert('Setting update नहीं हुई',error.message);else setSettings(next)};
 const changePwd=async()=>{if(pwd.length<6)return Alert.alert('Password','कम से कम 6 characters रखें।');const{error}=await supabase.auth.updateUser({password:pwd});if(error)Alert.alert('Password update नहीं हुआ',error.message);else{setPwd('');Alert.alert('Success','Password updated!')}};
 const unblock=async(id:string)=>{if(!user)return;const{data,error}=await supabase.from('contacts').delete().match({requester_id:user.id,responder_id:id,status:'blocked'}).select();if(error||!data?.length)Alert.alert('Unblock नहीं हुआ',error?.message||'Permission denied');else load()};
 return <SafeAreaView style={[s.root,light&&{backgroundColor:'#F8FAFC'}]} edges={['top']}><ScrollView contentContainerStyle={s.content}><Text style={[s.title,light&&{color:'#0F172A'}]}>सेटिंग्स</Text>
 <View style={[s.card,light&&{backgroundColor:'#FFFFFF',borderColor:'#E2E8F0'}]}><Text style={[s.heading,{color:colors.text}]}><User size={18}/> प्रोफ़ाइल</Text><View style={s.profileRow}><View style={s.avatar}>{profile?.avatar_url?<Image source={{uri:profile.avatar_url}} style={s.avatarImg}/>:<Text style={s.avatarText}>{(profile?.display_name||'?')[0].toUpperCase()}</Text>}</View><View style={{flex:1}}><Text style={[s.name,{color:colors.text}]}>{profile?.display_name||'यूज़र'}</Text><Text style={[s.muted,{color:colors.textSecondary}]}>@{profile?.username||'user'}</Text><TouchableOpacity style={s.photoBtn} onPress={uploadAvatar} disabled={uploadingAvatar}>{uploadingAvatar?<ActivityIndicator color="#60A5FA"/>:<Camera color="#60A5FA" size={16}/>}<Text style={s.photoText}>Change Photo</Text></TouchableOpacity></View></View><TextInput style={[s.input,{backgroundColor:colors.input,borderColor:colors.border,color:colors.inputText}]} value={name} onChangeText={setName} placeholder="Display Name" placeholderTextColor="#64748B"/><TextInput style={[s.input,{height:88,textAlignVertical:'top',backgroundColor:colors.input,borderColor:colors.border,color:colors.inputText}]} value={bio} onChangeText={setBio} multiline placeholder="Bio" placeholderTextColor="#64748B"/><TouchableOpacity style={s.primary} onPress={save} disabled={saving}>{saving?<ActivityIndicator color="#fff"/>:<Save color="#fff" size={18}/>}<Text style={s.btnText}>Save Profile</Text></TouchableOpacity></View>
 <View style={[s.card,light&&{backgroundColor:'#FFFFFF',borderColor:'#E2E8F0'}]}><Text style={[s.heading,{color:colors.text}]}>Account</Text><Text style={[s.muted,{color:colors.textSecondary}]}>Email: {user?.email}</Text><Text style={[s.muted,{color:colors.textSecondary}]}>Provider: {user?.app_metadata?.provider||'Email & Password'}</Text>{(!user?.app_metadata?.provider||user.app_metadata.provider==='email')&&<><TextInput style={[s.input,{backgroundColor:colors.input,borderColor:colors.border,color:colors.inputText}]} value={pwd} onChangeText={setPwd} secureTextEntry placeholder="New Password" placeholderTextColor="#64748B"/><TouchableOpacity style={s.secondary} onPress={changePwd}><KeyRound color="#fff" size={18}/><Text style={s.btnText}>Change Password</Text></TouchableOpacity></>}</View>
 {blocked.length>0&&<View style={[s.card,light&&{backgroundColor:'#FFFFFF',borderColor:'#E2E8F0'}]}><Text style={[s.heading,{color:colors.text}]}><Ban size={18}/> Blocked Users</Text>{blocked.map((b:any)=><View key={b.responder_id} style={s.blockRow}><View><Text style={[s.name,{color:colors.text}]}>{b.profiles?.display_name||'User'}</Text><Text style={[s.muted,{color:colors.textSecondary}]}>@{b.profiles?.username}</Text></View><TouchableOpacity onPress={()=>unblock(b.responder_id)}><Text style={s.green}>Unblock</Text></TouchableOpacity></View>)}</View>}
 {settings&&<><View style={[s.card,light&&{backgroundColor:'#FFFFFF',borderColor:'#E2E8F0'}]}><Text style={[s.heading,{color:colors.text}]}><Shield size={18}/> Privacy</Text><Text style={[s.muted,{color:colors.textSecondary}]}>कौन contact/friend request भेज सकता है</Text>{[['everyone','Everyone'],['contacts_of_contacts','Contacts of contacts'],['nobody','Nobody']].map(([v,l])=><TouchableOpacity key={v} style={s.option} onPress={()=>updateSetting({contact_requests:v})}><View style={[s.radio,settings.contact_requests===v&&s.radioOn]}/><Text style={[s.optionText,{color:colors.text}]}>{l}</Text></TouchableOpacity>)}</View><View style={[s.card,light&&{backgroundColor:'#FFFFFF',borderColor:'#E2E8F0'}]}><View style={s.switchRow}><View><Text style={[s.heading,{color:colors.text}]}><Bell size={18}/> Notifications</Text><Text style={[s.muted,{color:colors.textSecondary}]}>Contact/Friend Requests</Text></View><Switch value={!!settings.notify_contact_requests} onValueChange={v=>updateSetting({notify_contact_requests:v})} trackColor={{true:'#2563EB'}}/></View></View></>}
 <View style={[s.card,light&&{backgroundColor:'#FFFFFF',borderColor:'#E2E8F0'}]}><Text style={[s.heading,{color:colors.text}]}>Theme</Text><Text style={[s.muted,{color:colors.textSecondary}]}>मोबाइल के साथ Automatic या Light/Dark चुनें</Text><View style={{flexDirection:'row',gap:8}}>{[['system','Automatic'],['light','Light'],['dark','Dark']].map(([v,l])=><TouchableOpacity key={v} onPress={()=>setMode(v as any)} style={[s.secondary,{flex:1,backgroundColor:mode===v?'#2563EB':colors.surfaceAlt,borderWidth:1,borderColor:colors.border}]}><Text style={[s.btnText,mode!==v&&{color:colors.text}]}>{l}</Text></TouchableOpacity>)}</View></View>
 <View style={[s.card,{backgroundColor:colors.card,borderColor:'#7F1D1D'}]}><Text style={[s.heading,{color:'#F87171'}]}><Trash2 size={18}/> Danger Zone</Text><TouchableOpacity onPress={()=>Alert.alert('Delete Account','Website version में भी Delete Account button का backend action अभी wired नहीं है।')}><Text style={s.red}>Delete Account</Text></TouchableOpacity></View><TouchableOpacity style={[s.logout,light&&{backgroundColor:'#FFFFFF'}]} onPress={signOut}><LogOut color="#F87171" size={19}/><Text style={s.red}>Sign Out</Text></TouchableOpacity></ScrollView></SafeAreaView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#0B1220'},content:{padding:18,paddingBottom:50,gap:14},title:{fontSize:27,fontWeight:'800',color:'#fff',marginBottom:2},card:{backgroundColor:'#172033',borderRadius:18,padding:16,borderWidth:1,borderColor:'#1E293B',gap:12},heading:{color:'#fff',fontSize:17,fontWeight:'800'},profileRow:{flexDirection:'row',alignItems:'center',gap:12},avatar:{width:60,height:60,borderRadius:30,backgroundColor:'#2563EB',alignItems:'center',justifyContent:'center',overflow:'hidden'},avatarImg:{width:'100%',height:'100%'},avatarText:{color:'#fff',fontSize:23,fontWeight:'800'},name:{color:'#fff',fontWeight:'700'},photoBtn:{flexDirection:'row',alignItems:'center',gap:6,marginTop:7},photoText:{color:'#60A5FA',fontWeight:'700'},muted:{color:'#94A3B8',fontSize:13,marginTop:2},input:{backgroundColor:'#0B1220',borderWidth:1,borderColor:'#334155',borderRadius:13,paddingHorizontal:13,paddingVertical:12,color:'#fff'},primary:{height:46,borderRadius:12,backgroundColor:'#2563EB',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},secondary:{height:44,borderRadius:12,backgroundColor:'#475569',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},btnText:{color:'#fff',fontWeight:'700'},searchBtn:{backgroundColor:'#2563EB',borderRadius:16,padding:15,flexDirection:'row',alignItems:'center',gap:12},searchTitle:{color:'#fff',fontWeight:'800'},blockRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:6},green:{color:'#4ADE80',fontWeight:'700'},option:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:6},radio:{width:18,height:18,borderRadius:9,borderWidth:2,borderColor:'#64748B'},radioOn:{borderColor:'#22C55E',backgroundColor:'#22C55E'},optionText:{color:'#E2E8F0'},switchRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},red:{color:'#F87171',fontWeight:'700'},logout:{backgroundColor:'#172033',borderRadius:16,padding:16,flexDirection:'row',alignItems:'center',gap:9}});
