import React,{useCallback,useEffect,useState} from 'react';
import {SafeAreaView} from 'react-native-safe-area-context';
import {View,Text,TouchableOpacity,StyleSheet,ActivityIndicator,Alert} from 'react-native';
import {ArrowLeft,UserPlus,UserCheck,MessageCircle,X,Ban,UserMinus} from 'lucide-react-native';
import {supabase} from '../../lib/supabase'; import {useAuth} from '../../context/AuthContext';
export default function UserProfileScreen({route,navigation}:any){
 const profileId=route.params?.profileId; const {user}=useAuth(); const [profile,setProfile]=useState<any>(); const [contact,setContact]=useState<any>(); const [loading,setLoading]=useState(true);
 const load=useCallback(async()=>{if(!profileId||!user)return;setLoading(true);const [{data:p},{data:c}]=await Promise.all([supabase.from('profiles').select('*').eq('id',profileId).maybeSingle(),supabase.from('contacts').select('*').or(`and(requester_id.eq.${user.id},responder_id.eq.${profileId}),and(requester_id.eq.${profileId},responder_id.eq.${user.id})`)]);setProfile(p);const rows=c??[];const priority:any={accepted:3,pending:2,blocked:1};setContact(rows.sort((a:any,b:any)=>(priority[b.status]||0)-(priority[a.status]||0))[0]??null);setLoading(false)},[profileId,user]);
 useEffect(()=>{load()},[load]);
 const add=async()=>{const{error}=await supabase.from('contacts').insert({requester_id:user!.id,responder_id:profileId,status:'pending'});if(error)Alert.alert('Request नहीं भेजी',error.message);else load()};
 const accept=async()=>{if(!contact)return;const{error}=await supabase.from('contacts').update({status:'accepted'}).eq('id',contact.id);if(error)Alert.alert('Accept नहीं हुआ',error.message);else load()};
 const reject=async()=>{if(!contact)return;const{error}=await supabase.from('contacts').delete().eq('id',contact.id);if(error)Alert.alert('Decline नहीं हुआ',error.message);else load()};
 const remove=async()=>{if(!contact)return;const{error}=await supabase.from('contacts').delete().or(`and(requester_id.eq.${user?.id},responder_id.eq.${profileId}),and(requester_id.eq.${profileId},responder_id.eq.${user?.id})`);if(error)Alert.alert('Remove नहीं हुआ',error.message);else load()};
 const block=async()=>{if(!user)return;await supabase.from('contacts').delete().or(`and(requester_id.eq.${user.id},responder_id.eq.${profileId}),and(requester_id.eq.${profileId},responder_id.eq.${user.id})`);const{error}=await supabase.from('contacts').insert({requester_id:user.id,responder_id:profileId,status:'blocked'});if(error)Alert.alert('Block नहीं हुआ',error.message);else load()};
 const unblock=async()=>{if(!contact)return;const{error}=await supabase.from('contacts').delete().eq('id',contact.id);if(error)Alert.alert('Unblock नहीं हुआ',error.message);else load()};
 const chat=async()=>{const{data,error}=await supabase.rpc('create_private_conversation',{other_user_id:profileId});if(error||!data)return Alert.alert('Chat नहीं खुली',error?.message);navigation.navigate('Chat',{conversationId:data,name:profile?.display_name,otherUserId:profileId})};
 if(loading)return <View style={s.center}><ActivityIndicator color="#22C55E"/></View>;
 const incoming=contact?.status==='pending'&&contact?.responder_id===user?.id;
 return <SafeAreaView style={s.root}><View style={s.head}><TouchableOpacity onPress={()=>navigation.goBack()}><ArrowLeft color="#fff"/></TouchableOpacity><Text style={s.title}>प्रोफ़ाइल</Text></View><View style={s.card}><View style={s.avatar}><Text style={s.avatarText}>{(profile?.display_name||'?')[0].toUpperCase()}</Text></View><Text style={s.name}>{profile?.display_name||'यूज़र'}</Text><Text style={s.username}>@{profile?.username||'user'}</Text>
 {!contact&&<TouchableOpacity style={s.primary} onPress={add}><UserPlus color="#fff" size={19}/><Text style={s.btnText}>Friend Request भेजें</Text></TouchableOpacity>}
 {contact?.status==='pending'&&!incoming&&<View style={s.pending}><Text style={s.pendingText}>Friend Request भेजी गई</Text></View>}
 {incoming&&<View style={s.actions}><TouchableOpacity style={s.primarySmall} onPress={accept}><UserCheck color="#fff" size={18}/><Text style={s.btnText}>Accept</Text></TouchableOpacity><TouchableOpacity style={s.decline} onPress={reject}><X color="#fff" size={18}/><Text style={s.btnText}>Decline</Text></TouchableOpacity></View>}
 {contact?.status==='accepted'&&<><View style={s.friend}><UserCheck color="#22C55E" size={18}/><Text style={s.friendText}>Friends</Text></View><TouchableOpacity style={s.primary} onPress={chat}><MessageCircle color="#fff" size={19}/><Text style={s.btnText}>Message</Text></TouchableOpacity><TouchableOpacity style={s.dangerOutline} onPress={remove}><UserMinus color="#F87171" size={18}/><Text style={s.dangerText}>Remove Friend</Text></TouchableOpacity></>}
 {contact?.status==='blocked'?<TouchableOpacity style={s.primary} onPress={unblock}><UserPlus color="#fff" size={18}/><Text style={s.btnText}>Unblock</Text></TouchableOpacity>:<TouchableOpacity style={s.dangerOutline} onPress={block}><Ban color="#F87171" size={18}/><Text style={s.dangerText}>Block</Text></TouchableOpacity>}
 </View></SafeAreaView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#070D18'},center:{flex:1,backgroundColor:'#070D18',alignItems:'center',justifyContent:'center'},head:{height:60,flexDirection:'row',alignItems:'center',gap:18,paddingHorizontal:18,borderBottomWidth:1,borderBottomColor:'#172033'},title:{color:'#fff',fontSize:20,fontWeight:'700'},card:{alignItems:'center',padding:28},avatar:{width:92,height:92,borderRadius:46,backgroundColor:'#1D4ED8',alignItems:'center',justifyContent:'center'},avatarText:{color:'#fff',fontSize:36,fontWeight:'800'},name:{color:'#fff',fontSize:24,fontWeight:'800',marginTop:14},username:{color:'#94A3B8',marginTop:4,marginBottom:28},primary:{height:48,paddingHorizontal:20,borderRadius:12,backgroundColor:'#2563EB',flexDirection:'row',gap:9,alignItems:'center',justifyContent:'center',minWidth:220},btnText:{color:'#fff',fontWeight:'700'},pending:{backgroundColor:'#172033',paddingHorizontal:18,paddingVertical:13,borderRadius:12},pendingText:{color:'#CBD5E1'},actions:{flexDirection:'row',gap:12},primarySmall:{backgroundColor:'#16A34A',paddingHorizontal:20,height:46,borderRadius:12,flexDirection:'row',alignItems:'center',gap:7},decline:{backgroundColor:'#DC2626',paddingHorizontal:20,height:46,borderRadius:12,flexDirection:'row',alignItems:'center',gap:7},friend:{flexDirection:'row',gap:7,alignItems:'center',marginBottom:16},friendText:{color:'#22C55E',fontWeight:'700'},dangerOutline:{marginTop:12,height:44,paddingHorizontal:18,borderRadius:12,borderWidth:1,borderColor:'#7F1D1D',flexDirection:'row',gap:7,alignItems:'center',justifyContent:'center'},dangerText:{color:'#F87171',fontWeight:'700'}});
